# name: CI/CD with Astro

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20.8.0'

#       - name: Install Dependencies
#         run: npm install

#       - name: Build Astro App
#         run: npm run build
  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '20.8.0'

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Lint with ESLint
  #       run: npm run lint

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to Hosting Platform
  #       run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --yes
